### ISSUE TITLE
Board is at VC3, source is at VB2?

### ISSUE THREAD

**Issue by ElDominio** [turboedge/SpeedyBoards#2]
I saw that there's aa VC3 for sale, but the source only goes to an old revision. Can the source be updated? It is a very good reference for electronic design.

**Comment by rickyrockrat** [comment]
I bought a UA4C but no source, so I have no idea what I really have. I wish I had realized this before I bought it. I would have found something else.

**Comment by turboedge** [comment]
The files are now posted, sorry for the delay.

**Comment by rickyrockrat** [comment]
Thanks! I just built the speeduino from source using this project:
https://github.com/rickyrockrat/speeduino-build

Are there any files I should know about as far as pin mapping? I will work through the schematic and verify the pins are right, but didn't know if you need to supply a header file.  Thanks for the board, BTW! I hope to have my 1uzfe running here soon.

**Comment by turboedge** [comment]
Sorry you lost me. Verify what pins, header file? I hope your project goes smoothly.
